# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
 push:
  branches: [master]
 pull_request:
  branches: '*'

jobs:
 build:
  runs-on: ubuntu-latest

  strategy:
   matrix:
    node-version: [10.x, 12.x, 14.x]

  steps:
   - uses: actions/checkout@v2
   - name: Use Node.js ${{ matrix.node-version }}
     uses: actions/setup-node@v1
     env:
      GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_DB_URL: ${{ secrets.FIREBASE_DB_URL }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      FIREBASE_MSG_SENDER_ID: ${{ secrets.FIREBASE_MSG_SENDER_ID }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      COOKIEBOT_CONSENT_DECLARATION: ${{ secrets.COOKIEBOT_CONSENT_DECLARATION }}
      COOKIEBOT_CONSENT_HEAD: ${{ secrets.COOKIEBOT_CONSENT_HEAD }}
      TAWKTO: ${{ secrets.TAWKTO }}
      COOKIEBOT_CONSENT_HEAD_DATA_CBID: ${{ secrets.COOKIEBOT_CONSENT_HEAD_DATA_CBID }}
     with:
      node-version: ${{ matrix.node-version }}
   - run: ./startup.sh
   - run: npm i
   - name: Run ESLint
     run: eslint . --ext .js,.jsx,.ts,.tsx
   - run: CI=false NODE_ENV=production npm ci
   - run: CI=false npm run build --if-present
